name: lint.yml

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ecs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: cs2pr

      - uses: ramsey/composer-install@v3
        with:
          dependency-versions: "highest"

      - run: |
          vendor/bin/ecs check --ansi --no-progress-bar --output-format=checkstyle | cs2pr

  psalm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'

      - uses: ramsey/composer-install@v3
        with:
          dependency-versions: "highest"

      - run: |
          vendor/bin/psalm --version
          vendor/bin/psalm \
            --force-jit \
            --output-format=github \
            --taint-analysis \
            --report=reports/psalm-results.sarif \
            --show-info=true

      - uses: actions/upload-artifact@v5
        if: always()
        with:
          path: ./reports/psalm-results.sarif
          name: psalm-results.sarif

      - uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ./reports/psalm-results.sarif
          category: psalm

  rector:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      repository-projects: read

    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'

      - uses: ramsey/composer-install@v3
        with:
          dependency-versions: "highest"

      - uses: actions/cache@v3
        with:
          path: ./runtime/rector.cache
          key: ${{ runner.os }}-rector-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-rector-

      - run: vendor/bin/rector --ansi

      - run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Rector found issues. Please fix them before merging.";
            git --no-pager diff;
            exit 1;
          else
            echo "No changes detected by Rector.";
          fi
